name: Windows VS Build

on: [push, pull_request]
# TODO x64 and Win32
jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        arch: [x64, Win32]

    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build
      run: |
        msbuild .\windows\hidapi.sln /p:Configuration=Release /p:Platform=${{ matrix.arch }}
        ./bootstrap
        ./configure
        make -j
    - name: Test
      run: |
        hidtest/hidtest
